services:
  nginx:
    image: nginx:1.27.0
    container_name: lead-status-nginx
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/lead-status-panel
    ports:
      - "8080:80"
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm.Dockerfile
    container_name: lead-status-php-fpm
    volumes:
      - ./:/var/www/lead-status-panel
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/hosts:/etc/hosts

  php-cli:
    build:
      context: .
      dockerfile: docker/php-cli.Dockerfile
    container_name: lead-status-php-cli
    volumes:
      - ~/.ssh:/home/www-data/.ssh
      - ~/.bash_history:/home/www-data/.bash_history
      - ./:/var/www/lead-status-panel
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/hosts:/etc/hosts
    tty: true