services:
  apache:
    image: php:8.2-apache
    container_name: lead-status-apache
    volumes:
      - ./:/var/www/lead-status-panel
      - ./docker/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    ports:
      - "8080:80"
    depends_on:
      - php-cli

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm.Dockerfile
    container_name: lead-status-php-fpm
    volumes:
      - ./:/var/www/lead-status-panel
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/hosts:/etc/hosts

  php-cli:
    build:
      context: .
      dockerfile: docker/php-cli.Dockerfile
    container_name: lead-status-php-cli
    volumes:
      - ~/.ssh:/home/www-data/.ssh
      - ~/.bash_history:/home/www-data/.bash_history
      - ./:/var/www/lead-status-panel
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./docker/php/hosts:/etc/hosts
    tty: true